"""empty message

Revision ID: aff59f2d821b
Revises: 99575010ed4b
Create Date: 2025-06-25 20:20:23.177959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aff59f2d821b'
down_revision = '99575010ed4b'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('businesses', sa.Column('number_of_dissolution_delays', sa.Integer(), nullable=True))
    op.add_column('businesses_version', sa.Column('number_of_dissolution_delays', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses_version', 'number_of_dissolution_delays')
    op.drop_column('businesses', 'number_of_dissolution_delays')
       # ### end Alembic commands ###
